sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

language: java

jdk:
  - oraclejdk8
  
script: 
  - chmod 700 ./mvnw
  - ./mvnw clean compile
  
env:
  global:
  - SONATYPE_USERNAME=ralscha23
  
after_success:
- python addsettings.py
- mvn clean deploy -DskipTests=true --settings ~/.m2/mySettings.xml

cache:
  directories:
  - $HOME/.m2